/*
  _cursesWinConsts.hpp
 */
#ifndef _CURSESWINCONSTS_HPP
#define _CURSESWINCONSTS_HPP

// color pair values
enum CursesColors {
  none,
  _WHITE_TEXT,
  _BLACK_TEXT
} ;

// window index constants
enum _WINS {
  _MAINWIN,
  _PIDWIN,
  _USERWIN,
  _PRWIN,
  _NIWIN,
  _VIRTWIN,
  _RESWIN,
  _SHRWIN,
  _SWIN,
  _PROCCPUWIN,
  _PROCMEMWIN,
  _PROCTIMEWIN,
  _COMMANDWIN,
  _TOPWIN, 
  _TASKSWIN,
  _CPUWIN,
  _MEMWIN,
  _TASKSTOTALWIN,
  _TASKSRUNNINGWIN,
  _TASKSSLEEPINGWIN,
  _TASKSSTOPPEDWIN,
  _TASKSZOMBIEWIN,
  _CPUUSWIN,
  _CPUSYWIN,
  _CPUNIWIN,
  _CPUIDWIN,
  _CPUWAWIN,
  _CPUHIWIN,
  _CPUSIWIN,
  _CPUSTWIN,
  _MIBTOTALWIN,
  _MIBFREEWIN,
  _MIBUSEDWIN,
  _MIBBUFFCACHEWIN,
  _MIBSWAPTOTALWIN,
  _MIBSWAPFREEWIN,
  _MIBSWAPUSEDWIN,
  _MIBMEMAVAILWIN,
  _CPUGRAPHWIN,
  _MEMGRAPHWIN,
  _USERINPUTWIN,
  _HELPWIN // 40
};

// window position constantsconstants
#define _YOFFSET 6

// process window size constants
#define _PIDWINCOLS 7
#define _USERWINCOLS 8
#define _PRWINCOLS 3
#define _NIWINCOLS 3
#define _VIRTWINCOLS 7
#define _RESWINCOLS 6
#define _SHRWINCOLS 6
#define _SWINCOLS 1
#define _PROCCPUWINCOLS 5
#define _PROCMEMWINCOLS 5
#define _PROCTIMEWINCOLS 9
#define _COMMANDWINCOLS 40

// tasks window size constants


// task label wins
#define _TASKSLABELCOLS 6

// tasks data wins
#define _TASKSDATAWINCOLS 4
#define _TASKSDATASTARTY 1
#define _TASKSTOTALSTARTX 6
#define _TASKSRUNSTARTX 17
#define _TASKSSLEEPSTARTX 30
#define _TASKSSTOPSTARTX 44
#define _TASKSZOMBSTARTX 57

// CPU data wins
#define _CPUDATAWINCOLS 5
#define _CPUDATASTARTY 2
#define _CPUUSSTARTX 8
#define _CPUSYSTARTX 17
#define _CPUNISTARTX 26
#define _CPUIDSTARTX 35
#define _CPUWASTARTX 44
#define _CPUHISTARTX 53
#define _CPUSISTARTX 62
#define _CPUSTSTARTX 71

// main/swap mem data wins
#define _MEMDATAWINCOLS 9
#define _MAINMEMSTARTY 3
#define _MAINMEMTOTALSTARTX 9
#define _MAINMEMFREESTARTX 25
#define _MAINMEMUSEDSTARTX 40
#define _MAINMEMBUFFCACHESTARTX 55
#define _SWAPMEMSTARTY 4
#define _SWAPMEMTOTALSTARTX 9
#define _SWAPMEMFREESTARTX 25
#define _SWAPMEMUSEDSTARTX 40
#define _MEMAVAILSTARTX 55

#endif
